import React, { useState } from 'react';

// Mock Payload matching the structure generated by HandoverReportService
const MOCK_REPORT = {
  orderId: 'ORDER_001',
  status: 'COMPLETED',
  generatedAt: new Date().toISOString(),
  openings: [
    {
      reference: 'W-01',
      room: 'Living Room',
      steps: [
        { name: 'ENTRY_AUTH', status: 'COMPLETED', completedAt: '08:00 AM' },
        { name: 'LEVELLING', status: 'COMPLETED', completedAt: '08:30 AM' },
        { name: 'MECHANICAL_FIXING', status: 'COMPLETED', completedAt: '09:15 AM' },
      ]
    }
  ],
  complianceHighlights: {
    overrides: [
      { openingReference: 'W-01', step: 'MECHANICAL_FIXING', status: 'APPROVED', reason: 'Substrate crumbled', approvedBy: 'SUP_99' }
    ],
    outOfToleranceMeasurements: [
      { openingReference: 'W-01', step: 'LEVELLING', axis: 'X', reading: 4, toleranceUsed: 2 }
    ],
    discrepancies: []
  }
};

export const HandoverReportViewer: React.FC = () => {
  const [report] = useState(MOCK_REPORT);

  const hasHighlights = report.complianceHighlights.overrides.length > 0 || 
                        report.complianceHighlights.outOfToleranceMeasurements.length > 0 ||
                        report.complianceHighlights.discrepancies.length > 0;

  return (
    <div className="p-8 max-w-5xl mx-auto bg-white min-h-screen text-slate-800 font-sans print:p-0 print:m-0">
      
      {/* Header */}
      <div className="border-b-4 border-slate-900 pb-6 mb-8 flex justify-between items-end">
        <div>
          <h1 className="text-4xl font-bold uppercase tracking-tight">Installation Handover</h1>
          <p className="text-slate-500 mt-2">Order Ref: <strong className="text-slate-900">{report.orderId}</strong></p>
        </div>
        <div className="text-right text-sm text-slate-500">
          Generated: {new Date(report.generatedAt).toLocaleDateString()}
        </div>
      </div>

      {/* Compliance Highlights (FR-7.3) */}
      {hasHighlights && (
        <div className="bg-red-50 border-l-8 border-red-600 p-6 mb-12 print:break-inside-avoid">
          <h2 className="text-2xl font-bold text-red-800 mb-4 flex items-center">
            <span className="mr-3">⚠️</span> Compliance Highlights & Deviations
          </h2>
          <p className="text-red-900 mb-6 font-medium">
            The following exceptions were recorded and approved during the installation process.
          </p>
          
          {report.complianceHighlights.overrides.length > 0 && (
            <div className="mb-6">
              <h3 className="font-bold text-red-900 mb-2 border-b border-red-200 pb-1">Safety Overrides</h3>
              <ul className="list-disc pl-6 text-red-800">
                {report.complianceHighlights.overrides.map((ov, i) => (
                  <li key={i} className="mb-1">
                    <strong>{ov.openingReference} ({ov.step}):</strong> {ov.reason} (Approved: {ov.approvedBy})
                  </li>
                ))}
              </ul>
            </div>
          )}

          {report.complianceHighlights.outOfToleranceMeasurements.length > 0 && (
            <div>
              <h3 className="font-bold text-red-900 mb-2 border-b border-red-200 pb-1">Out of Tolerance Measurements</h3>
              <ul className="list-disc pl-6 text-red-800">
                {report.complianceHighlights.outOfToleranceMeasurements.map((m, i) => (
                  <li key={i} className="mb-1">
                    <strong>{m.openingReference} ({m.step}):</strong> {m.axis}-Axis reading was {m.reading}mm (Tolerance limit: {m.toleranceUsed}mm)
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>
      )}

      {/* Opening Execution Timelines */}
      <div>
        <h2 className="text-2xl font-bold text-slate-800 mb-6 uppercase border-b-2 border-slate-200 pb-2">
          Execution Details
        </h2>
        
        {report.openings.map((opening, idx) => (
          <div key={idx} className="mb-10 print:break-inside-avoid">
            <h3 className="text-xl font-bold mb-4 bg-slate-100 p-3 rounded">
              {opening.reference} - {opening.room}
            </h3>
            
            <div className="pl-4 border-l-2 border-slate-300 ml-4">
              {opening.steps.map((step, sIdx) => (
                <div key={sIdx} className="relative pb-6">
                  {/* Timeline dot */}
                  <div className="absolute -left-6 w-3 h-3 bg-green-500 rounded-full mt-1.5 border border-white"></div>
                  
                  <div className="flex justify-between items-start">
                    <div>
                      <h4 className="font-bold text-slate-800">{step.name}</h4>
                      <p className="text-sm text-slate-500">Status: {step.status}</p>
                    </div>
                    <div className="text-sm font-mono text-slate-500 bg-slate-50 px-2 py-1 rounded border border-slate-200">
                      {step.completedAt}
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        ))}
      </div>

      {/* Signature Block */}
      <div className="mt-16 pt-8 border-t-2 border-slate-200 print:mt-auto print:break-inside-avoid">
        <p className="mb-12 text-slate-600 font-medium text-center">
          By signing below, I acknowledge that the installation was completed as detailed above, 
          including any explicit deviations or safety overrides.
        </p>
        
        <div className="flex justify-between gap-12">
          <div className="flex-1">
            <div className="border-b border-slate-400 h-10"></div>
            <p className="text-center text-sm font-bold mt-2 uppercase tracking-wide">Client Signature</p>
          </div>
          <div className="flex-1">
            <div className="border-b border-slate-400 h-10"></div>
            <p className="text-center text-sm font-bold mt-2 uppercase tracking-wide">Lead Installer Signature</p>
          </div>
        </div>
      </div>
    </div>
  );
};
