import fs from 'fs';

function fixFile(file) {
  let content = fs.readFileSync(file, 'utf8');
  // It's hard to regex unescaped newlines inside strings.
  // Instead, since these were generated by the scraper recently, 
  // let's look for description: '...' where there might be a newline before the closing quote.
  // Wait, an easier way is to just use a custom replacer script that looks for the exact error line
  // and fixes it, or we can just replace newlines in the description fields.
  
  // Since we injected this, let's fix the raw `description: '...` lines.
  // Actually, we can just replace all occurrences of:
  // "functionality.\nStandard:"
  content = content.replace(/functionality\.\nStandard:/g, 'functionality. Standard:');
  
  // Let's also catch any other newline inside description by doing a generic fix if there's any.
  // A regex for description: ' (anything with newlines) ' up to the next property.
  // It's safer to just fix the known instances if there are few. Let's do a blanket replace of literal newlines
  // that are preceded by a word character and followed by a word character or quote inside description strings.
  content = content.replace(/(description:\s*'(?:[^'\\]|\\.)*)(\n|\r\n)((?:[^'\\]|\\.)*')/g, '$1 $3');
  // run multiple times in case of multiple newlines
  content = content.replace(/(description:\s*'(?:[^'\\]|\\.)*)(\n|\r\n)((?:[^'\\]|\\.)*')/g, '$1 $3');
  content = content.replace(/(description:\s*'(?:[^'\\]|\\.)*)(\n|\r\n)((?:[^'\\]|\\.)*')/g, '$1 $3');
  
  // Fix specifically the one we saw if regex missed it
  content = content.replace(/functionality\.\r?\nStandard:/g, 'functionality. Standard:');

  fs.writeFileSync(file, content);
}

fixFile('src/data/productDetails.ts');
fixFile('src/data/products.ts');
console.log("Fixed newlines!");
