const Database = require('better-sqlite3');
const db = new Database('src/data/cantor/cantor.sqlite');
console.log(db.prepare("SELECT PREIS FROM PREISMAT WHERE PREISMATRIX='PVC_F100' AND KLASSE2='IGE' AND BREITE=1500 AND HOEHE=1500").get());
console.log(db.prepare("SELECT PREIS FROM PREISMAT WHERE PREISMATRIX='PVC_F100' AND KLASSE2='IG5' AND BREITE=1500 AND HOEHE=1500").get());
console.log("PRICE MAT IGE 1000x1000", db.prepare("SELECT PREIS FROM PREISMAT WHERE PREISMATRIX='PVC_F100' AND KLASSE2='IGE' AND BREITE=1000 AND HOEHE=1000").get());
console.log("PRICE MAT IG5 1000x1000", db.prepare("SELECT PREIS FROM PREISMAT WHERE PREISMATRIX='PVC_F100' AND KLASSE2='IG5' AND BREITE=1000 AND HOEHE=1000").get());
