export const PLACEHOLDER_UNVERIFIED_WEIGHT = "PLACEHOLDER_UNVERIFIED";

export const mockInstallationLists = [
  {
    "id": "mock-list-369264",
    "orderId": "369264",
    "status": "READY",
    "items": [
        {
            "id": "item-1",
            "itemNumber": 1,
            "type": "JOINERY",
            "category": "WINDOW",
            "description": "Window 2 chambers movable post",
            "quantity": 1,
            "width": 1265,
            "height": 1300,
            "system": "IGLO EDGE - WINDOWS",
            "color": "White",
            "weightKg": 71.35,
            "schematicUrl": "/order_images/item_1.png",
            "specs": [
                "Dimensions:",
                "1265 x 1300 mm",
                "- External color",
                "- White",
                "- Internal color",
                "- White",
                "- Core color",
                "- White",
                "- Gaskets color",
                "- Black",
                "Profiles:",
                "Frame 80001 (height 73mm, depth 82mm)",
                "Sash 80013, 76mm",
                "Movable post 80029, 78mm",
                "Under-sill / transport strip",
                "54123 - 30mm",
                "Glazing bead style",
                "Rectangular",
                "- External application",
                "- Weld: V Perfect",
                "- Frame drainage: From the front",
                "- Sash drainage: From the bottom",
                "- Color of drainage caps: White",
                "- 6mm assembly holes: LEFT, RIGHT,",
                "- Roller blind/Venetian blind/Guide rails: Roller shutter",
                "- Frame reinforcement: Full",
                "Field 1: Left turn passive, gearshift (R-SBP-L)",
                "- Fitting system: Maco Multi Matic",
                "- Hinge Type: Standardowy (obwiedniowy)",
                "- Color of the covers: White",
                "- 4 mushroom cam keeps (if technologically feasible)",
                "Field 2: Tilt & turn right-hand active (UR-SC-P)",
                "- Fitting system: Maco Multi Matic",
                "- Height of the handle from the bottom edge of the sash: 520",
                "- Handle type: Aluminum handle DUBLIN",
                "- Handle color (inside): White",
                "- Color of the covers: White",
                "- 4 mushroom cam keeps (if technologically feasible)",
                "Roller shutter",
                "- Revision: From the bottom",
                "- Zaślepka obudowy bocznej: Tak",
                "- Kolor zaślepek obudowy bocznej: White",
                "- Adapter: Adapter Iglo Energy/Iglo EDGE",
                "- Slat Type: Aluminium slats 37 mm",
                "- Color of the slats: 02 - White, RAL 9016",
                "- Slats perforation: Perforated slats",
                "- Color of the bottom rail: 02 - White, RAL 9016",
                "- Type of limiters 1: Drutex Bumper (mounted in the lower rail of the curtain)",
                "- Type of guides: PVC",
                "- Left outer guide rail: Guide one-sided with mosquito net 61mm RN",
                "- Right outer guide rail: Guide one-sided with mosquito net 61mm RN",
                "- Color of the guides: White,",
                "- Drive Type I: Motor Simu T5 roller 60mm 10Nm overload",
                "- Control side I: Left (from the inside)",
                "- Mosquito net type: Roll-up (vertical)",
                "- Kolor siatki moskitiery: Black",
                "- Color of the mosquito net bottom bar: 02 - White",
                "- Safeguard 1: Blocking hangers",
                "U-value",
                "0,82 W/m2*K",
                "Details",
                "Field: 1",
                "Exposed glass size (EGS): 438.50 x 1072",
                "Field: 2",
                "Exposed glass size (EGS): 438.50 x 1072",
                "Rw (C;Ctr) = 36 (-2,-7) dB",
                "Ra1 = 34; Ra2 = 29; Ra2R = 27",
                "Infills",
                "Field: 1",
                "Filling",
                "4 th/U18/4/U18/4 th",
                "Spacer type",
                "Glazing thickness",
                "Ug Coefficient",
                "G Coefficient",
                "Lt Coefficient",
                "Rw-value",
                "SHGC (Solar Heat Gain",
                "Coefficient)",
                "Glazing dimensions",
                "(U) Ultimate Gray (RAL 9023)",
                "48.0",
                "0.50",
                "0.53",
                "0.73",
                "33db",
                "0.46",
                "468.50 x 1102",
                "Field: 2",
                "Filling",
                "4 th/U18/4/U18/4 th",
                "Spacer type",
                "Glazing thickness",
                "Ug Coefficient",
                "G Coefficient",
                "Lt Coefficient",
                "Rw-value",
                "SHGC (Solar Heat Gain",
                "Coefficient)",
                "Glazing dimensions",
                "(U) Ultimate Gray (RAL 9023)",
                "48.0",
                "0.50",
                "0.53",
                "0.73",
                "33db",
                "0.46",
                "468.50 x 1102"
            ]
        },
        {
            "id": "item-2",
            "itemNumber": 2,
            "type": "JOINERY",
            "category": "DOOR",
            "description": "2-chambersbalcony door movable post",
            "quantity": 1,
            "width": 1280,
            "height": 2030,
            "system": "IGLO EDGE - WINDOWS",
            "color": "White",
            "weightKg": 107.9,
            "schematicUrl": "/order_images/item_2.png",
            "specs": [
                "Dimensions:",
                "1280 x 2030 mm",
                "- External color",
                "- White",
                "- Internal color",
                "- White",
                "- Core color",
                "- White",
                "- Gaskets color",
                "- Black",
                "Profiles:",
                "Frame 80001 (height 73mm, depth 82mm)",
                "Sash 80013, 76mm",
                "Movable post 80029, 78mm",
                "Under-sill / transport strip",
                "54123 - 30mm",
                "Glazing bead style",
                "Rectangular",
                "- External application",
                "- Weld: V Perfect",
                "- Frame drainage: From the front",
                "- Sash drainage: From the bottom",
                "- Color of drainage caps: White",
                "- 6mm assembly holes: LEFT, RIGHT,",
                "- Roller blind/Venetian blind/Guide rails: Roller shutter",
                "- Frame reinforcement: Full",
                "Field 1: Left turn passive, gearshift (R-SBP-L)",
                "- Fitting system: Maco Multi Matic",
                "- Turning sash with perimeter fittings",
                "- Hinge Type: Standardowy (obwiedniowy)",
                "- Color of the covers: White",
                "- 4 mushroom cam keeps (if technologically feasible)",
                "Field 2: Tilt & turn right-hand active (UR-SC-P)",
                "- Fitting system: Maco Multi Matic",
                "- Height of the handle from the bottom edge of the sash: 1070",
                "- Handle type: Aluminum handle DUBLIN",
                "- Handle color (inside): White",
                "- Color of the covers: White",
                "- 4 mushroom cam keeps (if technologically feasible)",
                "Roller shutter",
                "- Revision: From the bottom",
                "- Zaślepka obudowy bocznej: Tak",
                "- Kolor zaślepek obudowy bocznej: White",
                "- Adapter: Adapter Iglo Energy/Iglo EDGE",
                "- Slat Type: Aluminium slats 37 mm",
                "- Color of the slats: 02 - White, RAL 9016",
                "- Slats perforation: Perforated slats",
                "- Color of the bottom rail: 02 - White, RAL 9016",
                "- Type of limiters 1: Drutex Bumper (mounted in the lower rail of the curtain)",
                "- Type of guides: PVC",
                "- Left outer guide rail: Guide one-sided with mosquito net 61mm RN",
                "- Right outer guide rail: Guide one-sided with mosquito net 61mm RN",
                "- Color of the guides: White,",
                "- Drive Type I: Motor Simu T5 roller 60mm 10Nm overload",
                "- Control side I: Left (from the inside)",
                "- Mosquito net type: Roll-up (vertical)",
                "- Kolor siatki moskitiery: Black",
                "- Color of the mosquito net bottom bar: 02 - White",
                "- Safeguard 1: Blocking hangers",
                "U-value",
                "0,79 W/m2*K",
                "Details",
                "Field: 1",
                "Exposed glass size (EGS): 446 x 1802",
                "Field: 2",
                "Exposed glass size (EGS): 446 x 1802",
                "Rw (C;Ctr) = 36 (-2,-7) dB",
                "Ra1 = 34; Ra2 = 29; Ra2R = 27",
                "Infills",
                "Field: 1",
                "Filling",
                "4 th ESG/U18/4/U18/4 th ESG",
                "Spacer type",
                "Glazing thickness",
                "Ug Coefficient",
                "G Coefficient",
                "Lt Coefficient",
                "Rw-value",
                "SHGC (Solar Heat Gain",
                "Coefficient)",
                "Glazing dimensions",
                "(U) Ultimate Gray (RAL 9023)",
                "48.0",
                "0.50",
                "0.53",
                "0.73",
                "33db",
                "0.46",
                "476 x 1832",
                "Field: 2",
                "Filling",
                "4 th ESG/U18/4/U18/4 th ESG",
                "Spacer type",
                "Glazing thickness",
                "Ug Coefficient",
                "G Coefficient",
                "Lt Coefficient",
                "Rw-value",
                "SHGC (Solar Heat Gain",
                "Coefficient)",
                "Glazing dimensions",
                "(U) Ultimate Gray (RAL 9023)",
                "48.0",
                "0.50",
                "0.53",
                "0.73",
                "33db",
                "0.46",
                "476 x 1832"
            ]
        },
        {
            "id": "item-3",
            "itemNumber": 3,
            "type": "JOINERY",
            "category": "DOOR",
            "description": "2-chambersbalcony door movable post",
            "quantity": 1,
            "width": 1270,
            "height": 2030,
            "system": "IGLO EDGE - WINDOWS",
            "color": "White",
            "weightKg": 107.22,
            "schematicUrl": "/order_images/item_3.png",
            "specs": [
                "Dimensions:",
                "1270 x 2030 mm",
                "- External color",
                "- White",
                "- Internal color",
                "- White",
                "- Core color",
                "- White",
                "- Gaskets color",
                "- Black",
                "Profiles:",
                "Frame 80001 (height 73mm, depth 82mm)",
                "Sash 80013, 76mm",
                "Movable post 80029, 78mm",
                "Under-sill / transport strip",
                "54123 - 30mm",
                "Glazing bead style",
                "Rectangular",
                "- External application",
                "- Weld: V Perfect",
                "- Frame drainage: From the front",
                "- Sash drainage: From the bottom",
                "- Color of drainage caps: White",
                "- 6mm assembly holes: LEFT, RIGHT,",
                "- Roller blind/Venetian blind/Guide rails: Roller shutter",
                "- Frame reinforcement: Full",
                "Field 1: Left turn passive, gearshift (R-SBP-L)",
                "- Fitting system: Maco Multi Matic",
                "- Hinge Type: Standardowy (obwiedniowy)",
                "- Color of the covers: White",
                "- 4 mushroom cam keeps (if technologically feasible)",
                "Field 2: Tilt & turn right-hand active (UR-SC-P)",
                "- Fitting system: Maco Multi Matic",
                "- Height of the handle from the bottom edge of the sash: 1070",
                "- Handle type: Aluminum handle DUBLIN",
                "- Handle color (inside): White",
                "- Color of the covers: White",
                "- 4 mushroom cam keeps (if technologically feasible)",
                "Roller shutter",
                "- Revision: From the bottom",
                "- Zaślepka obudowy bocznej: Tak",
                "- Kolor zaślepek obudowy bocznej: White",
                "- Adapter: Adapter Iglo Energy/Iglo EDGE",
                "- Slat Type: Aluminium slats 37 mm",
                "- Color of the slats: 02 - White, RAL 9016",
                "- Slats perforation: Perforated slats",
                "- Color of the bottom rail: 02 - White, RAL 9016",
                "- Type of limiters 1: Drutex Bumper (mounted in the lower rail of the curtain)",
                "- Type of guides: PVC",
                "- Left outer guide rail: Guide one-sided with mosquito net 61mm RN",
                "- Right outer guide rail: Guide one-sided with mosquito net 61mm RN",
                "- Color of the guides: White,",
                "- Drive Type I: Motor Simu T5 roller 60mm 10Nm overload",
                "- Control side I: Right (from the inside)",
                "- Mosquito net type: Roll-up (vertical)",
                "- Kolor siatki moskitiery: Black",
                "- Color of the mosquito net bottom bar: 02 - White",
                "- Safeguard 1: Blocking hangers",
                "U-value",
                "0,79 W/m2*K",
                "Details",
                "Field: 1",
                "Exposed glass size (EGS): 441 x 1802",
                "Field: 2",
                "Exposed glass size (EGS): 441 x 1802",
                "Rw (C;Ctr) = 36 (-2,-7) dB",
                "Ra1 = 34; Ra2 = 29; Ra2R = 27",
                "Infills",
                "Field: 1",
                "Filling",
                "4 th ESG/U18/4/U18/4 th ESG",
                "Spacer type",
                "Glazing thickness",
                "Ug Coefficient",
                "G Coefficient",
                "Lt Coefficient",
                "Rw-value",
                "SHGC (Solar Heat Gain",
                "Coefficient)",
                "Glazing dimensions",
                "(U) Ultimate Gray (RAL 9023)",
                "48.0",
                "0.50",
                "0.53",
                "0.73",
                "33db",
                "0.46",
                "471 x 1832",
                "Field: 2",
                "Filling",
                "4 th ESG/U18/4/U18/4 th ESG",
                "Spacer type",
                "Glazing thickness",
                "Ug Coefficient",
                "G Coefficient",
                "Lt Coefficient",
                "Rw-value",
                "SHGC (Solar Heat Gain",
                "Coefficient)",
                "Glazing dimensions",
                "(U) Ultimate Gray (RAL 9023)",
                "48.0",
                "0.50",
                "0.53",
                "0.73",
                "33db",
                "0.46",
                "471 x 1832"
            ]
        },
        {
            "id": "item-4",
            "itemNumber": 4,
            "type": "JOINERY",
            "category": "WINDOW",
            "description": "Window 2 chambers movable post",
            "quantity": 1,
            "width": 1270,
            "height": 1040,
            "system": "IGLO EDGE - WINDOWS",
            "color": "White",
            "weightKg": 58.87,
            "schematicUrl": "/order_images/item_4.jpeg",
            "specs": [
                "Dimensions:",
                "1270 x 1040 mm",
                "- External color",
                "- White",
                "- Internal color",
                "- White",
                "- Core color",
                "- White",
                "- Gaskets color",
                "- Black",
                "Profiles:",
                "Frame 80001 (height 73mm, depth 82mm)",
                "Sash 80013, 76mm",
                "Movable post 80029, 78mm",
                "Under-sill / transport strip",
                "54123 - 30mm",
                "Glazing bead style",
                "Rectangular",
                "- External application",
                "- Weld: V Perfect",
                "- Frame drainage: From the front",
                "- Sash drainage: From the bottom",
                "- Color of drainage caps: White",
                "- 6mm assembly holes: LEFT, RIGHT,",
                "- Frame reinforcement: Full",
                "Field 1: Left turn passive, gearshift (R-SBP-L)",
                "- Fitting system: Maco Multi Matic",
                "- Hinge Type: Standardowy (obwiedniowy)",
                "- Color of the covers: White",
                "- 4 mushroom cam keeps (if technologically feasible)",
                "Field 2: Tilt & turn right-hand active (UR-SC-P)",
                "- Fitting system: Maco Multi Matic",
                "- Height of the handle from the bottom edge of the sash: 420",
                "- Handle type: Aluminum handle DUBLIN",
                "- Handle color (inside): White",
                "- Color of the covers: White",
                "- 4 mushroom cam keeps (if technologically feasible)",
                "U-value",
                "0,84 W/m2*K",
                "Details",
                "Field: 1",
                "Exposed glass size (EGS): 441 x 812",
                "Field: 2",
                "Exposed glass size (EGS): 441 x 812",
                "Rw (C;Ctr) = 36 (-2,-7) dB",
                "Ra1 = 34; Ra2 = 29; Ra2R = 27",
                "Infills",
                "Field: 1",
                "Filling",
                "4 th/U18/4 Satinovo matte/U18/4 th",
                "Spacer type",
                "Glazing thickness",
                "Ug Coefficient",
                "G Coefficient",
                "Lt Coefficient",
                "Rw-value",
                "SHGC (Solar Heat Gain",
                "Coefficient)",
                "Glazing dimensions",
                "(U) Ultimate Gray (RAL 9023)",
                "48.0",
                "0.50",
                "0.52",
                "0.72",
                "33db",
                "0.46",
                "471 x 842",
                "Field: 2",
                "Filling",
                "4 th/U18/4 Satinovo matte/U18/4 th",
                "Spacer type",
                "Glazing thickness",
                "Ug Coefficient",
                "G Coefficient",
                "Lt Coefficient",
                "Rw-value",
                "SHGC (Solar Heat Gain",
                "Coefficient)",
                "Glazing dimensions",
                "(U) Ultimate Gray (RAL 9023)",
                "48.0",
                "0.50",
                "0.52",
                "0.72",
                "33db",
                "0.46",
                "471 x 842"
            ]
        },
        {
            "id": "item-5",
            "itemNumber": 5,
            "type": "JOINERY",
            "category": "WINDOW",
            "description": "1-chamber window",
            "quantity": 1,
            "width": 860,
            "height": 830,
            "system": "IGLO EDGE - WINDOWS",
            "color": "White",
            "weightKg": 32.11,
            "schematicUrl": "/order_images/item_5.jpeg",
            "specs": [
                "Dimensions:",
                "860 x 830 mm",
                "- External color",
                "- White",
                "- Internal color",
                "- White",
                "- Core color",
                "- White",
                "- Gaskets color",
                "- Black",
                "Profiles:",
                "Frame 80001 (height 73mm, depth 82mm)",
                "Sash 80013, 76mm",
                "Under-sill / transport strip",
                "54123 - 30mm",
                "Glazing bead style",
                "Rectangular",
                "- External application",
                "- Weld: V Perfect",
                "- Frame drainage: From the front",
                "- Sash drainage: From the bottom",
                "- Color of drainage caps: White",
                "- 6mm assembly holes: LEFT, RIGHT,",
                "- Frame reinforcement: Full",
                "Field 1: Left hand tilt & turn Perimeter fittings",
                "- Fitting system: Maco Multi Matic",
                "- Height of the handle from the bottom edge of the sash: 320",
                "- Handle type: Aluminum handle DUBLIN",
                "- Handle color (inside): White",
                "- Color of the covers: White",
                "- 4 mushroom cam keeps (if technologically feasible)",
                "U-value",
                "0,84 W/m2*K",
                "Details",
                "Field: 1",
                "Exposed glass size (EGS): 632 x 602",
                "Rw (C;Ctr) = 36 (-2,-7) dB",
                "Ra1 = 34; Ra2 = 29; Ra2R = 27",
                "Infills",
                "Field: 1",
                "Filling",
                "4 th/U18/4 Satinovo matte/U18/4 th",
                "Spacer type",
                "Glazing thickness",
                "Ug Coefficient",
                "G Coefficient",
                "Lt Coefficient",
                "Rw-value",
                "SHGC (Solar Heat Gain",
                "Coefficient)",
                "Glazing dimensions",
                "(U) Ultimate Gray (RAL 9023)",
                "48.0",
                "0.50",
                "0.52",
                "0.72",
                "33db",
                "0.46",
                "662 x 632"
            ]
        },
        {
            "id": "item-6",
            "itemNumber": 6,
            "type": "JOINERY",
            "category": "WINDOW",
            "description": "1-chamber window",
            "quantity": 1,
            "width": 560,
            "height": 820,
            "system": "IGLO EDGE - WINDOWS",
            "color": "White",
            "weightKg": 22.57,
            "schematicUrl": "/order_images/item_6.jpeg",
            "specs": [
                "Dimensions:",
                "560 x 820 mm",
                "- External color",
                "- White",
                "- Internal color",
                "- White",
                "- Core color",
                "- White",
                "- Gaskets color",
                "- Black",
                "Profiles:",
                "Frame 80001 (height 73mm, depth 82mm)",
                "Sash 80013, 76mm",
                "Under-sill / transport strip",
                "54123 - 30mm",
                "Glazing bead style",
                "Rectangular",
                "- External application",
                "- Weld: V Perfect",
                "- Frame drainage: From the front",
                "- Sash drainage: From the bottom",
                "- Color of drainage caps: White",
                "- 6mm assembly holes: LEFT, RIGHT,",
                "- Frame reinforcement: Full",
                "Field 1: Left hand tilt & turn Perimeter fittings",
                "- Fitting system: Maco Multi Matic",
                "- Height of the handle from the bottom edge of the sash: 320",
                "- Handle type: Aluminum handle DUBLIN",
                "- Handle color (inside): White",
                "- Color of the covers: White",
                "- 4 mushroom cam keeps (if technologically feasible)",
                "U-value",
                "0,91 W/m2*K",
                "Details",
                "Field: 1",
                "Exposed glass size (EGS): 332 x 592",
                "Rw (C;Ctr) = 36 (-2,-7) dB",
                "Ra1 = 34; Ra2 = 29; Ra2R = 27",
                "Infills",
                "Field: 1",
                "Filling",
                "4 th/U18/4 Satinovo matte/U18/4 th",
                "Spacer type",
                "Glazing thickness",
                "Ug Coefficient",
                "G Coefficient",
                "Lt Coefficient",
                "Rw-value",
                "SHGC (Solar Heat Gain",
                "Coefficient)",
                "Glazing dimensions",
                "(U) Ultimate Gray (RAL 9023)",
                "48.0",
                "0.50",
                "0.52",
                "0.72",
                "33db",
                "0.46",
                "362 x 622"
            ]
        },
        {
            "id": "item-7",
            "itemNumber": 7,
            "type": "JOINERY",
            "category": "WINDOW",
            "description": "1-chamber window",
            "quantity": 1,
            "width": 560,
            "height": 820,
            "system": "IGLO EDGE - WINDOWS",
            "color": "White",
            "weightKg": 22.57,
            "schematicUrl": "/order_images/item_7.jpeg",
            "specs": [
                "Dimensions:",
                "560 x 820 mm",
                "- External color",
                "- White",
                "- Internal color",
                "- White",
                "- Core color",
                "- White",
                "- Gaskets color",
                "- Black",
                "Profiles:",
                "Frame 80001 (height 73mm, depth 82mm)",
                "Sash 80013, 76mm",
                "Under-sill / transport strip",
                "54123 - 30mm",
                "Glazing bead style",
                "Rectangular",
                "- External application",
                "- Weld: V Perfect",
                "- Frame drainage: From the front",
                "- Sash drainage: From the bottom",
                "- Color of drainage caps: White",
                "- 6mm assembly holes: LEFT, RIGHT,",
                "- Frame reinforcement: Full",
                "Field 1: Tilt & turn right-hand Perimeter fittings",
                "- Fitting system: Maco Multi Matic",
                "- Height of the handle from the bottom edge of the sash: 320",
                "- Handle type: Aluminum handle DUBLIN",
                "- Handle color (inside): White",
                "- Color of the covers: White",
                "- 4 mushroom cam keeps (if technologically feasible)",
                "U-value",
                "0,91 W/m2*K",
                "Details",
                "Field: 1",
                "Exposed glass size (EGS): 332 x 592",
                "Rw (C;Ctr) = 36 (-2,-7) dB",
                "Ra1 = 34; Ra2 = 29; Ra2R = 27",
                "Infills",
                "Field: 1",
                "Filling",
                "4 th/U18/4 Satinovo matte/U18/4 th",
                "Spacer type",
                "Glazing thickness",
                "Ug Coefficient",
                "G Coefficient",
                "Lt Coefficient",
                "Rw-value",
                "SHGC (Solar Heat Gain",
                "Coefficient)",
                "Glazing dimensions",
                "(U) Ultimate Gray (RAL 9023)",
                "48.0",
                "0.50",
                "0.52",
                "0.72",
                "33db",
                "0.46",
                "362 x 622"
            ]
        },
        {
            "id": "item-8",
            "itemNumber": 8,
            "type": "JOINERY",
            "category": "WINDOW",
            "description": "Window 3-chambers movable post",
            "quantity": 1,
            "width": 1270,
            "height": 1300,
            "system": "IGLO EDGE - WINDOWS",
            "color": "White",
            "weightKg": 71.53,
            "schematicUrl": "/order_images/item_8.jpeg",
            "specs": [
                "Dimensions:",
                "1270 x 1300 mm",
                "- External color",
                "- White",
                "- Internal color",
                "- White",
                "- Core color",
                "- White",
                "- Gaskets color",
                "- Black",
                "Profiles:",
                "Frame 80001 (height 73mm, depth 82mm)",
                "Sash 80013, 76mm",
                "Post 80021, 98mm",
                "Movable post 80029, 78mm",
                "Under-sill / transport strip",
                "54123 - 30mm",
                "Glazing bead style",
                "Rectangular",
                "- External application",
                "- Weld: V Perfect",
                "- Frame drainage: From the front",
                "- Sash drainage: From the bottom",
                "- Post drainage: From the front",
                "- Color of drainage caps: White",
                "- 6mm assembly holes: LEFT, RIGHT,",
                "- Roller blind/Venetian blind/Guide rails: Roller shutter",
                "- Frame reinforcement: Full",
                "Field 1: Left hand tilt & turn czynne (UR-SC-L)",
                "- Fitting system: Maco Multi Matic",
                "- Height of the handle from the bottom edge of the sash: 420",
                "- Handle type: Aluminum handle DUBLIN",
                "- Handle color (inside): White",
                "- Color of the covers: White",
                "- 4 mushroom cam keeps (if technologically feasible)",
                "Field 2: Turn right passive, gearshift (R-SBP-P)",
                "- Fitting system: Maco Multi Matic",
                "- Hinge Type: Standardowy (obwiedniowy)",
                "- Color of the covers: White",
                "- 4 mushroom cam keeps (if technologically feasible)",
                "Field 3: Fixed glazing in the frame (FIX)",
                "Roller shutter",
                "- Revision: From the bottom",
                "- Zaślepka obudowy bocznej: Tak",
                "- Kolor zaślepek obudowy bocznej: White",
                "- Adapter: Adapter Iglo Energy/Iglo EDGE",
                "- Slat Type: Aluminium slats 37 mm",
                "- Color of the slats: 02 - White, RAL 9016",
                "- Slats perforation: Perforated slats",
                "- Color of the bottom rail: 02 - White, RAL 9016",
                "- Type of limiters 1: Drutex Bumper (mounted in the lower rail of the curtain)",
                "- Type of guides: PVC",
                "- Left outer guide rail: Guide one-sided with mosquito net 61mm RN",
                "- Right outer guide rail: Guide one-sided with mosquito net 61mm RN",
                "- Color of the guides: White,",
                "- Drive Type I: Motor Simu T5 roller 60mm 10Nm overload",
                "- Control side I: Right (from the inside)",
                "- Mosquito net type: Roll-up (vertical)",
                "- Kolor siatki moskitiery: Black",
                "- Color of the mosquito net bottom bar: 02 - White",
                "- Safeguard 1: Blocking hangers",
                "U-value",
                "0,86 W/m2*K",
                "Details",
                "Field: 1",
                "Exposed glass size (EGS): 441 x 746",
                "Field: 2",
                "Exposed glass size (EGS): 441 x 746",
                "Field: 3",
                "Exposed glass size (EGS): 1124 x 228",
                "Rw (C;Ctr) = 34 (-1,-5) dB",
                "Ra1 = 33; Ra2 = 29; Ra2R = 27",
                "Infills",
                "Field: 1",
                "Filling",
                "4 th/U20/4 Satinovo matte/U18/4 th",
                "Spacer type",
                "Glazing thickness",
                "Ug Coefficient",
                "G Coefficient",
                "Lt Coefficient",
                "Rw-value",
                "SHGC (Solar Heat Gain",
                "Coefficient)",
                "Glazing dimensions",
                "(U) Ultimate Gray (RAL 9023)",
                "50.0",
                "0.50",
                "0.52",
                "0.72",
                "33db",
                "0.46",
                "471 x 776",
                "Field: 2",
                "Filling",
                "4 th/U20/4 Satinovo matte/U18/4 th",
                "Spacer type",
                "Glazing thickness",
                "Ug Coefficient",
                "G Coefficient",
                "Lt Coefficient",
                "Rw-value",
                "SHGC (Solar Heat Gain",
                "Coefficient)",
                "Glazing dimensions",
                "(U) Ultimate Gray (RAL 9023)",
                "50.0",
                "0.50",
                "0.52",
                "0.72",
                "33db",
                "0.46",
                "471 x 776",
                "Field: 3",
                "Filling",
                "4 th/U20/4 Satinovo matte/U18/4 th",
                "Spacer type",
                "Glazing thickness",
                "Ug Coefficient",
                "G Coefficient",
                "Lt Coefficient",
                "Rw-value",
                "SHGC (Solar Heat Gain",
                "Coefficient)",
                "Glazing dimensions",
                "(U) Ultimate Gray (RAL 9023)",
                "50.0",
                "0.50",
                "0.52",
                "0.72",
                "33db",
                "0.46",
                "1160 x 264.50"
            ]
        },
        {
            "id": "item-9",
            "itemNumber": 9,
            "type": "NON_JOINERY",
            "category": "ACCESSORY",
            "description": "Flat bar P04000023, 40x2,3mm 6000mm",
            "quantity": 10,
            "color": "White",
            "specs": [
                "Item No. 9",
                "Quantity:   10",
                "P04000023 - Flat bar P04000023, 40x2,3mm 6000mm",
                "- Length: 6000 mm",
                "- Color: White"
            ]
        },
        {
            "id": "item-10",
            "itemNumber": 10,
            "type": "JOINERY",
            "category": "SLIDER",
            "description": "Iglo Edge Slide A (2 kw.) otw. na prawo",
            "quantity": 1,
            "width": 2000,
            "height": 2100,
            "system": "IGLO EDGE SLIDE",
            "color": "White",
            "weightKg": 179.39,
            "schematicUrl": "/order_images/item_10.jpeg",
            "specs": [
                "Dimensions:",
                "2000 x 2100 mm",
                "- External color",
                "- White",
                "- Internal color",
                "- White",
                "- Core color",
                "- White",
                "- Gaskets color",
                "- Black",
                "Profiles:",
                "Frame Edge Slide",
                "Stable post from Edge Slide sash",
                "Sash Edge Slide",
                "Sash Edge Slide sash bottom",
                "Glazing bead style",
                "Rectangular",
                "- External application",
                "- Weld: V Perfect",
                "- Frame drainage: From the front",
                "- Sash drainage: From the bottom",
                "- Color of drainage caps: White",
                "- Roller blind/Venetian blind/Guide rails: Roller shutter",
                "- Frame reinforcement: Full",
                "50103 Extension 15mm (depth 70mm) I5",
                "- Length: 2100 mm",
                "- Color: OUT: White / IN: White",
                "- Position: Left",
                "- Aligning-to-the-outside",
                "- Reinforcement: Lack",
                "50103 Extension 15mm (depth 70mm) I5",
                "- Length: 2100 mm",
                "- Color: OUT: White / IN: White",
                "- Position: Left",
                "- Flush to the inside",
                "- Reinforcement: Lack",
                "50103 Extension 15mm (depth 70mm) I5",
                "- Length: 2100 mm",
                "- Color: OUT: White / IN: White",
                "- Position: Right",
                "- Aligning-to-the-outside",
                "- Reinforcement: Lack",
                "50103 Extension 15mm (depth 70mm) I5",
                "- Length: 2100 mm",
                "- Color: OUT: White / IN: White",
                "- Position: Right",
                "- Flush to the inside",
                "- Reinforcement: Lack",
                "Field 1: Opened to the right (HST-A-P)",
                "- Espagnolette type: Central position of the handle",
                "- Height of the handle from the bottom edge of the sash: 1020",
                "- Handle type: Iglo Edge Slide 2-sided handle + inside only insert",
                "- Handle color (inside): White",
                "- Color of the handle/pull (ext.): White",
                "- Type of insert: Standard insert lock, spacing: 45/00",
                "- Standard safety class of fittings",
                "Field 2: fixed Glazing w ramie HS (HSM-FIX)",
                "Roller shutter",
                "- External box color: White,",
                "- Internal box color: White,",
                "- Revision: From the forehead",
                "- Zaślepka obudowy bocznej: Tak",
                "- Kolor zaślepek obudowy bocznej: White",
                "- Adapter: Adapter ALU, Wood, frame renovation",
                "- Number of reinforcing consoles: 1",
                "- Slat Type: Aluminium slats 37 mm",
                "- Color of the slats: 02 - White, RAL 9016",
                "- Slats perforation: Perforated slats",
                "- Color of the bottom rail: 02 - White, RAL 9016",
                "- Type of limiters 1: Drutex Bumper (mounted in the lower rail of the curtain)",
                "- Type of guides: PVC",
                "- Left outer guide rail: Guide one-sided with mosquito net 61mm RN",
                "- Left guide rail on extension profile: Yes",
                "- Center guide: Double-sided guide with mosquito net 61mm RN",
                "- Right outer guide rail: Guide one-sided with mosquito net 61mm RN",
                "- Right guide rail on extension profile: Yes",
                "- Color of the guides: White,",
                "- Drive Type I: Motor Simu T5 roller 60mm 10Nm overload",
                "- Control side I: Left (from the inside)",
                "- Drive Type II: common drive",
                "- Control side II: z polem sasiadujacym po lewej (od wewnatrz)",
                "- Mosquito net type: Roll-up (vertical)",
                "- Kolor siatki moskitiery: Black",
                "- Color of the mosquito net bottom bar: 02 - White",
                "- Safeguard 1: Blocking hangers",
                "U-value",
                "0,75 W/m2*K",
                "Details",
                "Field: 1",
                "Exposed glass size (EGS): 807.25 x 1823",
                "Field: 2",
                "Exposed glass size (EGS): 889.75 x 1988",
                "Rw (C;Ctr) = 34 (-2,-6) dB",
                "Ra1 = 32; Ra2 = 28; Ra2R = 26",
                "Infills",
                "Field: 1",
                "Filling",
                "4 th ESG/U18/4/U18/4 th ESG",
                "Spacer type",
                "Glazing thickness",
                "Ug Coefficient",
                "G Coefficient",
                "Lt Coefficient",
                "Rw-value",
                "SHGC (Solar Heat Gain",
                "Coefficient)",
                "Glazing dimensions",
                "(U) Ultimate Gray (RAL 9023)",
                "48.0",
                "0.50",
                "0.53",
                "0.73",
                "33db",
                "0.46",
                "837.25 x 1853",
                "Field: 2",
                "Filling",
                "4 th ESG/U18/4/U18/4 th ESG",
                "Spacer type",
                "Glazing thickness",
                "Ug Coefficient",
                "G Coefficient",
                "Lt Coefficient",
                "Rw-value",
                "SHGC (Solar Heat Gain",
                "Coefficient)",
                "Glazing dimensions",
                "(U) Ultimate Gray (RAL 9023)",
                "48.0",
                "0.50",
                "0.53",
                "0.73",
                "33db",
                "0.46",
                "919.25 x 2017"
            ]
        },
        {
            "id": "item-11",
            "itemNumber": 11,
            "type": "NON_JOINERY",
            "category": "ACCESSORY",
            "description": "Flat bar P08000023, 80x2.3mm 6000mm",
            "quantity": 10,
            "color": "White",
            "specs": [
                "Item No. 11",
                "Quantity:   10",
                "P08000023 - Flat bar P08000023, 80x2.3mm 6000mm",
                "- Length: 6000 mm",
                "- Color: White"
            ]
        },
        {
            "id": "item-12",
            "itemNumber": 12,
            "type": "NON_JOINERY",
            "category": "ACCESSORY",
            "description": "STER_BLEBOX - uWIFI Blebox Shutterbox 230V controller",
            "quantity": 5,
            "specs": [
                "Item No. 12",
                "Quantity:   5",
                "STER_BLEBOX - uWIFI Blebox Shutterbox 230V controller Silniki : GEIGER,SIMU,YOODA_S,SELVE,SOMFY_WT"
            ]
        },
        {
            "id": "item-13",
            "itemNumber": 13,
            "type": "NON_JOINERY",
            "category": "ACCESSORY",
            "description": "BLEBOX_BI - remote 12 channel uRemote Basic Blebox white",
            "quantity": 1,
            "specs": [
                "Item No. 13",
                "Quantity:   1",
                "_BLEBOX_BI - remote 12 channel uRemote Basic Blebox white Silniki : GEIGER,SIMU,YOODA_S,SELVE,SOMFY_"
            ]
        },
        {
            "id": "item-14",
            "itemNumber": 14,
            "type": "NON_JOINERY",
            "category": "ACCESSORY",
            "description": "BLEBOX_BI - remote 12 channel uRemote Basic Blebox white",
            "quantity": 3,
            "specs": [
                "Item No. 14",
                "Quantity:   3",
                "_BLEBOX_BI - remote 12 channel uRemote Basic Blebox white Silniki : GEIGER,SIMU,YOODA_S,SELVE,SOMFY_"
            ]
        },
        {
            "id": "item-15",
            "itemNumber": 15,
            "type": "NON_JOINERY",
            "category": "ACCESSORY",
            "description": "Flat bar P10000023, 100x2.3mm 6000mm",
            "quantity": 1,
            "color": "White",
            "specs": [
                "Item No. 15",
                "Quantity:   1",
                "P10000023 - Flat bar P10000023, 100x2.3mm 6000mm",
                "- Length: 6000 mm",
                "- Color: White"
            ]
        },
        {
            "id": "item-16",
            "itemNumber": 16,
            "type": "JOINERY",
            "category": "DOOR",
            "description": "Single-sash balcony door",
            "quantity": 1,
            "width": 867,
            "height": 2125,
            "system": "IGLO EDGE - WINDOWS",
            "color": "Smooth basalt grey - REN. 701205-097",
            "weightKg": 73.93,
            "schematicUrl": "/order_images/item_16.jpeg",
            "specs": [
                "Dimensions:",
                "867 x 2125 mm",
                "- External color",
                "- Smooth basalt grey - REN. 701205-097",
                "- Internal color",
                "- White",
                "- Core color",
                "- White",
                "- Gaskets color",
                "- Black",
                "Profiles:",
                "Frame 80001 (height 73mm, depth 82mm)",
                "Sash 80013, 76mm",
                "Under-sill / transport strip",
                "54123 - 30mm",
                "Glazing bead style",
                "Rectangular",
                "- External application",
                "- Weld: V Perfect",
                "- Frame drainage: From the front",
                "- Sash drainage: From the bottom",
                "- Color of drainage caps: Basalt grey",
                "- 6mm assembly holes: LEFT, RIGHT,",
                "- Roller blind/Venetian blind/Guide rails: Roller shutter",
                "- Frame reinforcement: Full",
                "Field 1: Left hand tilt & turn Perimeter fittings",
                "- Fitting system: Maco Multi Matic",
                "- Height of the handle from the bottom edge of the sash: 1070",
                "- Handle type: Aluminum handle DUBLIN",
                "- Handle color (inside): White",
                "- Color of the covers: White",
                "- 4 mushroom cam keeps (if technologically feasible)",
                "Roller shutter",
                "- Type of roller shutter: Top mounted roller shutter",
                "- Width: 867.0",
                "- Height: 2340.0",
                "- Shutter installed on the window: Yes",
                "- Type of the box: BOX 215",
                "- External box color: Smooth basalt grey, 701205-097",
                "- Internal box color: White,",
                "- Revision: From the bottom",
                "- Zaślepka obudowy bocznej: Tak",
                "- Kolor zaślepek obudowy bocznej: White",
                "- Adapter: Adapter Iglo Energy/Iglo EDGE",
                "- Slat Type: Aluminium slats 37 mm",
                "- Color of the slats: 33 - Bazaltowy szary, RAL 7012",
                "- Slats perforation: Perforated slats",
                "- Color of the bottom rail: 33 - Bazaltowy szary, RAL 7012",
                "- Type of limiters 1: Drutex Bumper (mounted in the lower rail of the curtain)",
                "- Type of guides: PVC",
                "- Left outer guide rail: Guide one-sided 61mm RN",
                "- Right outer guide rail: Guide one-sided 61mm RN",
                "- Color of the guides: Smooth basalt grey, 701205-097",
                "- Drive Type I: Motor Simu T5 roller 60mm 10Nm overload",
                "- Control side I: Right (from the inside)",
                "- Safeguard 1: Blocking hangers",
                "U-value",
                "0,75 W/m2*K",
                "Details",
                "Field: 1",
                "Exposed glass size (EGS): 639 x 1897",
                "Rw (C;Ctr) = 36 (-2,-7) dB",
                "Ra1 = 34; Ra2 = 29; Ra2R = 27",
                "Lt Coefficient",
                "Rw-value",
                "SHGC (Solar Heat Gain",
                "Coefficient)",
                "Glazing dimensions",
                "0.64",
                "33db",
                "0.30",
                "669 x 1927"
            ]
        },
        {
            "id": "item-17",
            "itemNumber": 17,
            "type": "JOINERY",
            "category": "WINDOW",
            "description": "1-chamber window",
            "quantity": 1,
            "width": 867,
            "height": 1175,
            "system": "IGLO EDGE - WINDOWS",
            "color": "Smooth basalt grey - REN. 701205-097",
            "weightKg": 43.41,
            "schematicUrl": "/order_images/item_17.jpeg",
            "specs": [
                "Dimensions:",
                "867 x 1175 mm",
                "- External color",
                "- Smooth basalt grey - REN. 701205-097",
                "- Internal color",
                "- White",
                "- Core color",
                "- White",
                "- Gaskets color",
                "- Black",
                "Profiles:",
                "Frame 80001 (height 73mm, depth 82mm)",
                "Sash 80013, 76mm",
                "Under-sill / transport strip",
                "54123 - 30mm",
                "Glazing bead style",
                "Rectangular",
                "- External application",
                "- Weld: V Perfect",
                "- Frame drainage: From the front",
                "- Sash drainage: From the bottom",
                "- Color of drainage caps: Basalt grey",
                "- 6mm assembly holes: LEFT, RIGHT,",
                "- Roller blind/Venetian blind/Guide rails: Roller shutter",
                "- Frame reinforcement: Full",
                "Field 1: Tilt & turn right-hand Perimeter fittings",
                "- Fitting system: Maco Multi Matic",
                "- Height of the handle from the bottom edge of the sash: 420",
                "- Handle type: Aluminum handle DUBLIN",
                "- Handle color (inside): White",
                "- Color of the covers: White",
                "- 4 mushroom cam keeps (if technologically feasible)",
                "Roller shutter",
                "- Type of roller shutter: Top mounted roller shutter",
                "- Width: 867.0",
                "- Height: 1350.0",
                "- Shutter installed on the window: Yes",
                "- Type of the box: BOX 175",
                "- External box color: Smooth basalt grey, 701205-097",
                "- Internal box color: White,",
                "- Revision: From the bottom",
                "- Zaślepka obudowy bocznej: Tak",
                "- Kolor zaślepek obudowy bocznej: White",
                "- Adapter: Adapter Iglo Energy / Iglo Edge",
                "- Slat Type: Aluminium slats 37 mm",
                "- Color of the slats: 33 - Bazaltowy szary, RAL 7012",
                "- Slats perforation: Perforated slats",
                "- Color of the bottom rail: 33 - Bazaltowy szary, RAL 7012",
                "- Type of limiters 1: Buffer 20mm",
                "- Color of the limiters: Anthracite",
                "- Type of guides: PVC",
                "- Left outer guide rail: Guide one-sided 61mm RN 175 - SKS",
                "- Right outer guide rail: Guide one-sided 61mm RN 175 - SKS",
                "- Color of the guides: Smooth basalt grey, 701205-097",
                "- Drive Type I: Motor Simu T5 roller 60mm 10Nm overload",
                "- Control side I: Right (from the inside)",
                "- Safeguard 1: Blocking hangers",
                "U-value",
                "0,80 W/m2*K",
                "Details",
                "Field: 1",
                "Exposed glass size (EGS): 639 x 947",
                "Rw (C;Ctr) = 36 (-2,-7) dB",
                "Ra1 = 34; Ra2 = 29; Ra2R = 27",
                "Lt Coefficient",
                "Rw-value",
                "SHGC (Solar Heat Gain",
                "Coefficient)",
                "Glazing dimensions",
                "0.64",
                "33db",
                "0.30",
                "669 x 977",
                "Palletizing service",
                "Palette wooden",
                "Summary",
                "VAT",
                "GROSS",
                "NET",
                "Pallets",
                "0,00%",
                "23,60",
                "0,00",
                "23,60",
                "Products",
                "0,00%",
                "8 485,05",
                "0,00",
                "8 485,05",
                "Services",
                "0,00%",
                "1,00",
                "0,00",
                "1,00",
                "8 509,65",
                "8 509,65",
                "0,00",
                "Payment form: Bank transfer",
                "This offer is valid for 3 days from the date of issue."
            ]
        }
    ]
}
];
