SELECT DISTINCT SZYBA AS SingleGlassOption FROM (
    SELECT SZYBA1 AS SZYBA FROM CUSTOM_SZYBY WHERE SZYBA1 <> '-' AND SZYBA1 IS NOT NULL
    UNION
    SELECT SZYBA2 AS SZYBA FROM CUSTOM_SZYBY WHERE SZYBA2 <> '-' AND SZYBA2 IS NOT NULL
    UNION
    SELECT SZYBA3 AS SZYBA FROM CUSTOM_SZYBY WHERE SZYBA3 <> '-' AND SZYBA3 IS NOT NULL
    UNION
    SELECT SZYBA4 AS SZYBA FROM CUSTOM_SZYBY WHERE SZYBA4 <> '-' AND SZYBA4 IS NOT NULL
) AS AllPanes ORDER BY SingleGlassOption;
