export const IGLO_DOOR_COLORS: SwatchColor[] = [
  { name: 'White FX', hex: '#cccccc', image: '/assets/iglo5-doors/colors/white-fx-swatch.webp', windowImage: '/assets/iglo5-doors/colors/white-fx-door.webp' },
  { name: 'White Sand U-Matt', hex: '#cccccc', image: '/assets/iglo5-doors/colors/white-sand-u-matt-swatch.webp', windowImage: '/assets/iglo5-doors/colors/white-sand-u-matt-door.webp' },
  { name: 'Crown Platinum', hex: '#cccccc', image: '/assets/iglo5-doors/colors/crown-platinum-swatch.webp', windowImage: '/assets/iglo5-doors/colors/crown-platinum-door.webp' },
  { name: 'Creamy', hex: '#cccccc', image: '/assets/iglo5-doors/colors/creamy-swatch.webp', windowImage: '/assets/iglo5-doors/colors/creamy-door.webp' },
  { name: 'Pyrite', hex: '#cccccc', image: '/assets/iglo5-doors/colors/pyrite-swatch.webp', windowImage: '/assets/iglo5-doors/colors/pyrite-door.webp' },
  { name: 'Sheffield Oak Light', hex: '#cccccc', image: '/assets/iglo5-doors/colors/sheffield-oak-light-swatch.webp', windowImage: '/assets/iglo5-doors/colors/sheffield-oak-light-door.webp' },
  { name: 'Natural Oak', hex: '#cccccc', image: '/assets/iglo5-doors/colors/natural-oak-swatch.webp', windowImage: '/assets/iglo5-doors/colors/natural-oak-door.webp' },
  { name: 'Light Grey', hex: '#cccccc', image: '/assets/iglo5-doors/colors/light-grey-swatch.webp', windowImage: '/assets/iglo5-doors/colors/light-grey-door.webp' },
  { name: 'Grey', hex: '#cccccc', image: '/assets/iglo5-doors/colors/grey-swatch.webp', windowImage: '/assets/iglo5-doors/colors/grey-door.webp' },
  { name: 'Concrete Grey', hex: '#cccccc', image: '/assets/iglo5-doors/colors/concrete-grey-swatch.webp' },
  { name: 'Quartz Grey', hex: '#cccccc', image: '/assets/iglo5-doors/colors/quartz-grey-swatch.webp' },
  { name: 'Quartz Grey Smooth', hex: '#cccccc', image: '/assets/iglo5-doors/colors/quartz-grey-smooth-swatch.webp' },
  { name: 'Basalt Grey', hex: '#cccccc', image: '/assets/iglo5-doors/colors/basalt-grey-swatch.webp' },
  { name: 'Basalt Grey Smooth', hex: '#cccccc', image: '/assets/iglo5-doors/colors/basalt-grey-smooth-swatch.webp' },
  { name: 'Iron Glimmer Slate', hex: '#cccccc', image: '/assets/iglo5-doors/colors/iron-glimmer-slate-swatch.webp' },
  { name: 'Slate Grey Smooth', hex: '#cccccc', image: '/assets/iglo5-doors/colors/slate-grey-smooth-swatch.webp' },
  { name: 'Graphite Sand', hex: '#cccccc', image: '/assets/iglo5-doors/colors/graphite-sand-swatch.webp' },
  { name: 'Anthracite', hex: '#cccccc', image: '/assets/iglo5-doors/colors/anthracite-swatch.webp' },
  { name: 'Anthracite Smooth', hex: '#cccccc', image: '/assets/iglo5-doors/colors/anthracite-smooth-swatch.webp' },
  { name: 'Anthracite Ulti-Matt', hex: '#cccccc', image: '/assets/iglo5-doors/colors/anthracite-ulti-matt-swatch.webp' },
  { name: 'Jet black', hex: '#cccccc', image: '/assets/iglo5-doors/colors/jet-black-swatch.webp' },
  { name: 'Black Ulti-Matt', hex: '#cccccc', image: '/assets/iglo5-doors/colors/black-ulti-matt-swatch.webp' },
  { name: 'Golden Oak', hex: '#cccccc', image: '/assets/iglo5-doors/colors/golden-oak-swatch.webp' },
  { name: 'Turner Oak', hex: '#cccccc', image: '/assets/iglo5-doors/colors/turner-oak-swatch.webp' },
  { name: 'Turner Oak Toffee', hex: '#cccccc', image: '/assets/iglo5-doors/colors/turner-oak-toffee-swatch.webp' },
  { name: 'Turner Oak Walnut', hex: '#cccccc', image: '/assets/iglo5-doors/colors/turner-oak-walnut-swatch.webp' },
  { name: 'Winchester', hex: '#cccccc', image: '/assets/iglo5-doors/colors/winchester-swatch.webp' },
  { name: 'Oregon', hex: '#cccccc', image: '/assets/iglo5-doors/colors/oregon-swatch.webp' },
  { name: 'Douglas', hex: '#cccccc', image: '/assets/iglo5-doors/colors/douglas-swatch.webp' },
  { name: 'Nut', hex: '#cccccc', image: '/assets/iglo5-doors/colors/nut-swatch.webp' },
  { name: 'Dark Oak', hex: '#cccccc', image: '/assets/iglo5-doors/colors/dark-oak-swatch.webp' },
  { name: 'Palisander', hex: '#cccccc', image: '/assets/iglo5-doors/colors/palisander-swatch.webp' },
  { name: 'Macore', hex: '#cccccc', image: '/assets/iglo5-doors/colors/macore-swatch.webp' },
  { name: 'Mahogany', hex: '#cccccc', image: '/assets/iglo5-doors/colors/mahogany-swatch.webp' },
  { name: 'Chocolate Brown', hex: '#cccccc', image: '/assets/iglo5-doors/colors/chocolate-brown-swatch.webp' },
  { name: 'Shine deep bronze', hex: '#cccccc', image: '/assets/iglo5-doors/colors/shine-deep-bronze-swatch.webp' },
  { name: 'Moss green', hex: '#cccccc', image: '/assets/iglo5-doors/colors/moss-green-swatch.webp' },
  { name: 'Dark Green', hex: '#cccccc', image: '/assets/iglo5-doors/colors/dark-green-swatch.webp' },
  { name: 'Dark Red', hex: '#cccccc', image: '/assets/iglo5-doors/colors/dark-red-swatch.webp' },
  { name: 'Brylantowo Niebieski', hex: '#cccccc', image: '/assets/iglo5-doors/colors/brylantowo-niebieski-swatch.webp' },
  { name: 'Steel Blue', hex: '#cccccc', image: '/assets/iglo5-doors/colors/steel-blue-swatch.webp' },
];
