-- ============================================================
-- Cantor ERP Data Integration Tables
-- Migration: 016_cantor_data_integration.sql
-- ============================================================

-- 1. Cantor Products (Systems)
CREATE TABLE public.cantor_systems (
    cantor_key TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    type_class TEXT,
    pricing_group TEXT,
    base_price NUMERIC(10,2) DEFAULT 0,
    min_width INT,
    max_width INT,
    min_height INT,
    max_height INT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE POLICY "cantor_systems_select_all" ON public.cantor_systems FOR SELECT USING (true);
ALTER TABLE public.cantor_systems ENABLE ROW LEVEL SECURITY;

-- 2. Cantor Pricing Rules 
CREATE TABLE public.cantor_pricing_rules (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    system_key TEXT REFERENCES public.cantor_systems(cantor_key) ON DELETE CASCADE,
    description TEXT,
    rule_type TEXT,
    formula_string TEXT,
    modifier NUMERIC(10,4),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE POLICY "cantor_pricing_rules_select_all" ON public.cantor_pricing_rules FOR SELECT USING (true);
ALTER TABLE public.cantor_pricing_rules ENABLE ROW LEVEL SECURITY;


-- 3. Cantor Articles
CREATE TABLE public.cantor_articles (
    article_code TEXT PRIMARY KEY,
    system_key TEXT REFERENCES public.cantor_systems(cantor_key) ON DELETE CASCADE,
    name TEXT NOT NULL,
    price_value NUMERIC(10,2) DEFAULT 0,
    matrix_column_index INT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE POLICY "cantor_articles_select_all" ON public.cantor_articles FOR SELECT USING (true);
ALTER TABLE public.cantor_articles ENABLE ROW LEVEL SECURITY;


-- 4. Cantor Formula Matrices (Array-based optimization)
CREATE TABLE public.cantor_formula_matrices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matrix_name TEXT NOT NULL,       
    class_1 TEXT,                    
    class_2 TEXT,                    
    width INT NOT NULL DEFAULT 1,    
    height INT NOT NULL DEFAULT 1,   
    prices NUMERIC[],
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_cantor_matrix_lookup 
ON public.cantor_formula_matrices (matrix_name, class_1, class_2, width, height);

CREATE POLICY "cantor_formula_matrices_select_all" ON public.cantor_formula_matrices FOR SELECT USING (true);
ALTER TABLE public.cantor_formula_matrices ENABLE ROW LEVEL SECURITY;
